version: "3.9"
#https://realpython.com/django-development-with-docker-compose-and-machine/
#https://github.com/realpython/dockerizing-django

services:  
  db:
    restart: always
    image: postgres:latest

    env_file: .env    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - 
        type: bind
        source: ./data
        target: /var/lib/postgresql/data/

volumes:
  web-django:
      
