version: "3.9"
#https://realpython.com/django-development-with-docker-compose-and-machine/
#https://github.com/realpython/dockerizing-django

services:  
  wagtail:
    build: ./project
    env_file: .env    
    environment:
      DEBUG: 'False'
    expose:
      - "8000"
    links:
      - "db:db"
    volumes:
      - web-static:/app/static
    depends_on:
      - db

    
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - wagtail:wagtail
      
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_DB: wagtail_cms
      POSTGRES_PASSWORD: _dev9001_
    ports:
      - "5432:5432"
    volumes:
      - 
        type: bind
        source: ./data
        target: /var/lib/postgresql/data/

volumes:
  web-static:
  web-django:
      
